services:
  db:
    image: postgis/postgis:16-3.4
    container_name: biosentinel-db
    environment:
      POSTGRES_DB: biosentinel
      POSTGRES_USER: biosentinel
      POSTGRES_PASSWORD: biosentinel
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: